version: '3.8'

services:

  postgres-dianaTravel:
    container_name: postgres-dianaTravel
    image: postgres:13.12-alpine
    ports:
      - '5432:5432'
    hostname: postgres
    environment:
      POSTGRES_PASSWORD: postgres